{% set name = "tableschema-to-template" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d8d2250efb840e0ecb9012c5e879a82ef68f65dd86bdff574200fdfc978ff1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jsonschema >=1.0.0
    - pyyaml >=3.13
    - xlsxwriter >=1.2.8

test:
  imports:
    - tableschema_to_template
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - ts2xl.py --help

about:
  home: https://github.com/hubmapconsortium/tableschema-to-template
  summary: Given a Frictionless Table Schema, generates an Excel template with input validation
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kynan
